// <auto-generated />
using System;
using AkilliTarimSistemi.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkilliTarimSistemi.DAL.Migrations
{
    [DbContext(typeof(AkilliTarimDbContext))]
    [Migration("20260526212629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.GubreOnerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("HedefUrun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OneriTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("OnerilenAzot")
                        .HasColumnType("REAL");

                    b.Property<double>("OnerilenFosfor")
                        .HasColumnType("REAL");

                    b.Property<string>("OnerilenGubreCesidi")
                        .HasColumnType("TEXT");

                    b.Property<double>("OnerilenPotasyum")
                        .HasColumnType("REAL");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UygulamaZamani")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UygulandiMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("GubreOnerileri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.SensorVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Co2")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("IsikSiddeti")
                        .HasColumnType("REAL");

                    b.Property<double>("Nem")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OkumaZamani")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("Sicaklik")
                        .HasColumnType("REAL");

                    b.Property<int>("SulamaDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ToprakNemi")
                        .HasColumnType("REAL");

                    b.Property<double?>("pH")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("SensorVerileri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.SuAnalizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EC")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaynak")
                        .HasColumnType("TEXT");

                    b.Property<double>("Klor")
                        .HasColumnType("REAL");

                    b.Property<double>("Nitrat")
                        .HasColumnType("REAL");

                    b.Property<double>("Nitrit")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("Sertlik")
                        .HasColumnType("REAL");

                    b.Property<double>("Sodyum")
                        .HasColumnType("REAL");

                    b.Property<bool>("SulamayaUygun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("pH")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("SuAnalizleri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.Tarla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlanDekar")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OrtalamaSicaklik")
                        .HasColumnType("REAL");

                    b.Property<double?>("OrtalamaYagis")
                        .HasColumnType("REAL");

                    b.Property<string>("TarlaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToprakTipi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Tarlalar");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.ToprakAnalizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Azot")
                        .HasColumnType("REAL");

                    b.Property<double>("Fosfor")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("Kalsiyum")
                        .HasColumnType("REAL");

                    b.Property<double>("Magnezyum")
                        .HasColumnType("REAL");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("OrganikMadde")
                        .HasColumnType("REAL");

                    b.Property<double>("Potasyum")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToprakTipi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tuzluluk")
                        .HasColumnType("REAL");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("pH")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("ToprakAnalizleri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.UrunTavsiyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gerekce")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("GuvenSkoru")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TavsiyeEdilenUrun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TavsiyeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UygulandiMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("UrunTavsiyeleri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.VerimTahmini", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AltLimit")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("GuvenSkoru")
                        .HasColumnType("REAL");

                    b.Property<string>("KullanilanModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TahminTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("TahminiVerim")
                        .HasColumnType("REAL");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UstLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("VerimTahminleri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.YaprakAnalizi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AzotYaprak")
                        .HasColumnType("REAL");

                    b.Property<double>("Bakir")
                        .HasColumnType("REAL");

                    b.Property<double>("Cinko")
                        .HasColumnType("REAL");

                    b.Property<double>("Demir")
                        .HasColumnType("REAL");

                    b.Property<double>("FosforYaprak")
                        .HasColumnType("REAL");

                    b.Property<string>("GorselNot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GozlenenEksiklik")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("Mangan")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("PotasyumYaprak")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("TarlaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.ToTable("YaprakAnalizleri");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.GubreOnerisi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany()
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.SensorVerisi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany("SensorVerileri")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.SuAnalizi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany("SuAnalizleri")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.Tarla", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Tarlalar")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.ToprakAnalizi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany("ToprakAnalizleri")
                        .HasForeignKey("TarlaId");

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.UrunTavsiyesi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany()
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.VerimTahmini", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany()
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.YaprakAnalizi", b =>
                {
                    b.HasOne("AkilliTarimSistemi.Core.Entities.Tarla", "Tarla")
                        .WithMany("YaprakAnalizleri")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("Tarlalar");
                });

            modelBuilder.Entity("AkilliTarimSistemi.Core.Entities.Tarla", b =>
                {
                    b.Navigation("SensorVerileri");

                    b.Navigation("SuAnalizleri");

                    b.Navigation("ToprakAnalizleri");

                    b.Navigation("YaprakAnalizleri");
                });
#pragma warning restore 612, 618
        }
    }
}
